CREATE TABLE country (
       country_id  CHAR(3) PRIMARY KEY,
       country_name VARCHAR(200)
);
INSERT INTO country (country_id, country_name) VALUES
('AFG','Afghanistan'),
('ALA','Aland'),
('ALB','Albania'),
('DZA','Algeria'),
('ASM','American Samoa'),
('AND','Andorra'),
('AGO','Angola'),
('AIA','Anguilla'),
('ATA','Antarctica'),
('ATG','Antigua and Barbuda'),
('ARG','Argentina'),
('ARM','Armenia'),
('ABW','Aruba'),
('AUS','Australia'),
('AUT','Austria'),
('AZE','Azerbaijan'),
('BHS','Bahamas'),
('BHR','Bahrain'),
('BGD','Bangladesh'),
('BRB','Barbados'),
('BLR','Belarus'),
('BEL','Belgium'),
('BLZ','Belize'),
('BEN','Benin'),
('BMU','Bermuda'),
('BTN','Bhutan'),
('BOL','Bolivia'),
('BES','Bonaire'),
('BIH','Bosnia and Herzegovina'),
('BWA','Botswana'),
('BVT','Bouvet Island'),
('BRA','Brazil'),
('IOT','British Indian Ocean Territory'),
('VGB','British Virgin Islands'),
('BRN','Brunei'),
('BGR','Bulgaria'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('KHM','Cambodia'),
('CMR','Cameroon'),
('CAN','Canada'),
('CPV','Cape Verde'),
('CYM','Cayman Islands'),
('CAF','Central African Republic'),
('TCD','Chad'),
('CHL','Chile'),
('CHN','China'),
('CXR','Christmas Island'),
('CCK','Cocos [Keeling] Islands'),
('COL','Colombia'),
('COM','Comoros'),
('COK','Cook Islands'),
('CRI','Costa Rica'),
('HRV','Croatia'),
('CUB','Cuba'),
('CUW','Curacao'),
('CYP','Cyprus'),
('CZE','Czech Republic'),
('COD','Democratic Republic of the Congo'),
('DNK','Denmark'),
('DJI','Djibouti'),
('DMA','Dominica'),
('DOM','Dominican Republic'),
('TLS','East Timor'),
('ECU','Ecuador'),
('EGY','Egypt'),
('SLV','El Salvador'),
('GNQ','Equatorial Guinea'),
('ERI','Eritrea'),
('EST','Estonia'),
('ETH','Ethiopia'),
('FLK','Falkland Islands'),
('FRO','Faroe Islands'),
('FJI','Fiji'),
('FIN','Finland'),
('FRA','France'),
('GUF','French Guiana'),
('PYF','French Polynesia'),
('ATF','French Southern Territories'),
('GAB','Gabon'),
('GMB','Gambia'),
('GEO','Georgia'),
('DEU','Germany'),
('GHA','Ghana'),
('GIB','Gibraltar'),
('GRC','Greece'),
('GRL','Greenland'),
('GRD','Grenada'),
('GLP','Guadeloupe'),
('GUM','Guam'),
('GTM','Guatemala'),
('GGY','Guernsey'),
('GIN','Guinea'),
('GNB','Guinea-Bissau'),
('GUY','Guyana'),
('HTI','Haiti'),
('HMD','Heard Island and McDonald Islands'),
('HND','Honduras'),
('HKG','Hong Kong'),
('HUN','Hungary'),
('ISL','Iceland'),
('IND','India'),
('IDN','Indonesia'),
('IRN','Iran'),
('IRQ','Iraq'),
('IRL','Ireland'),
('IMN','Isle of Man'),
('ISR','Israel'),
('ITA','Italy'),
('CIV','Ivory Coast'),
('JAM','Jamaica'),
('JPN','Japan'),
('JEY','Jersey'),
('JOR','Jordan'),
('KAZ','Kazakhstan'),
('KEN','Kenya'),
('KIR','Kiribati'),
('XKX','Kosovo'),
('KWT','Kuwait'),
('KGZ','Kyrgyzstan'),
('LAO','Laos'),
('LVA','Latvia'),
('LBN','Lebanon'),
('LSO','Lesotho'),
('LBR','Liberia'),
('LBY','Libya'),
('LIE','Liechtenstein'),
('LTU','Lithuania'),
('LUX','Luxembourg'),
('MAC','Macao'),
('MKD','Macedonia'),
('MDG','Madagascar'),
('MWI','Malawi'),
('MYS','Malaysia'),
('MDV','Maldives'),
('MLI','Mali'),
('MLT','Malta'),
('MHL','Marshall Islands'),
('MTQ','Martinique'),
('MRT','Mauritania'),
('MUS','Mauritius'),
('MYT','Mayotte'),
('MEX','Mexico'),
('FSM','Micronesia'),
('MDA','Moldova'),
('MCO','Monaco'),
('MNG','Mongolia'),
('MNE','Montenegro'),
('MSR','Montserrat'),
('MAR','Morocco'),
('MOZ','Mozambique'),
('MMR','Myanmar [Burma]'),
('NAM','Namibia'),
('NRU','Nauru'),
('NPL','Nepal'),
('NLD','Netherlands'),
('NCL','New Caledonia'),
('NZL','New Zealand'),
('NIC','Nicaragua'),
('NER','Niger'),
('NGA','Nigeria'),
('NIU','Niue'),
('NFK','Norfolk Island'),
('PRK','North Korea'),
('MNP','Northern Mariana Islands'),
('NOR','Norway'),
('OMN','Oman'),
('PAK','Pakistan'),
('PLW','Palau'),
('PSE','Palestine'),
('PAN','Panama'),
('PNG','Papua New Guinea'),
('PRY','Paraguay'),
('PER','Peru'),
('PHL','Philippines'),
('PCN','Pitcairn Islands'),
('POL','Poland'),
('PRT','Portugal'),
('PRI','Puerto Rico'),
('QAT','Qatar'),
('COG','Republic of the Congo'),
('REU','Réunion'),
('ROU','Romania'),
('RUS','Russia'),
('RWA','Rwanda'),
('BLM','Saint Barthélemy'),
('SHN','Saint Helena'),
('KNA','Saint Kitts and Nevis'),
('LCA','Saint Lucia'),
('MAF','Saint Martin'),
('SPM','Saint Pierre and Miquelon'),
('VCT','Saint Vincent and the Grenadines'),
('WSM','Samoa'),
('SMR','San Marino'),
('STP','São Tomé and Príncipe'),
('SAU','Saudi Arabia'),
('SEN','Senegal'),
('SRB','Serbia'),
('SYC','Seychelles'),
('SLE','Sierra Leone'),
('SGP','Singapore'),
('SXM','Sint Maarten'),
('SVK','Slovakia'),
('SVN','Slovenia'),
('SLB','Solomon Islands'),
('SOM','Somalia'),
('ZAF','South Africa'),
('SGS','South Georgia and the South Sandwich Islands'),
('KOR','South Korea'),
('SSD','South Sudan'),
('ESP','Spain'),
('LKA','Sri Lanka'),
('SDN','Sudan'),
('SUR','Suriname'),
('SJM','Svalbard and Jan Mayen'),
('SWZ','Swaziland'),
('SWE','Sweden'),
('CHE','Switzerland'),
('SYR','Syria'),
('TWN','Taiwan'),
('TJK','Tajikistan'),
('TZA','Tanzania'),
('THA','Thailand'),
('TGO','Togo'),
('TKL','Tokelau'),
('TON','Tonga'),
('TTO','Trinidad and Tobago'),
('TUN','Tunisia'),
('TUR','Turkey'),
('TKM','Turkmenistan'),
('TCA','Turks and Caicos Islands'),
('TUV','Tuvalu'),
('UMI','U.S. Minor Outlying Islands'),
('VIR','U.S. Virgin Islands'),
('UGA','Uganda'),
('UKR','Ukraine'),
('ARE','United Arab Emirates'),
('GBR','United Kingdom'),
('USA','United States'),
('URY','Uruguay'),
('UZB','Uzbekistan'),
('VUT','Vanuatu'),
('VAT','Vatican City'),
('VEN','Venezuela'),
('VNM','Vietnam'),
('WLF','Wallis and Futuna'),
('ESH','Western Sahara'),
('YEM','Yemen'),
('ZMB','Zambia'),
('ZWE','Zimbabwe');

INSERT INTO state (state_id, state_name, country_id) VALUES
(1,'Kerala', 'IND');

CREATE TABLE district(
       district_id serial PRIMARY KEY,
       district_name VARCHAR(100),
       state_id integer,
       CONSTRAINT state_district_id_fkey FOREIGN KEY (state_id)
       REFERENCES state (state_id) MATCH SIMPLE 
       ON DELETE CASCADE
       );

INSERT INTO district (district_id, district_name, state_id) VALUES
(1,'Alappuzha',1),
(2,'Ernakulam',1),
(3,'Idukki',1),
(4,'Kannur',1),
(5,'Kasaragod',1),
(6,'Kollam',1),
(7,'Kottayam',1),
(8,'Kozhikode',1),
(9,'Malappuram',1),
(10,'Palakkad',1),
(11,'Pathanamthitta',1),
(12,'Thiruvananthapuram',1),
(13,'Thrissur',1),
(14,'Wayanad',1);

CREATE TABLE local_body_type(
       local_body_type_id serial PRIMARY KEY,
       local_body_type_name VARCHAR(100),
       country_id CHAR(3),
       CONSTRAINT local_body_type_country_id_fkey FOREIGN KEY (country_id)
       REFERENCES country (country_id) MATCH SIMPLE 
       ON DELETE CASCADE
);

INSERT INTO local_body_type(local_body_type_id, local_body_type_name, country_id) VALUES
(1,'Grama Panchayat','IND'),
(2,'Municipality','IND'),
(3,'Corporation','IND');

CREATE TABLE local_body(
       local_body_id serial PRIMARY KEY,
       local_body_name VARCHAR(100),
       district_id integer,
       local_body_type_id integer,
       CONSTRAINT local_body_district_fkey FOREIGN KEY (district_id)
       REFERENCES district (district_id) MATCH SIMPLE 
       ON DELETE CASCADE,
       CONSTRAINT local_body_type_fkey FOREIGN KEY (local_body_type_id)
       REFERENCES local_body_type (local_body_type_id) MATCH SIMPLE 
       ON DELETE CASCADE
);

INSERT INTO local_body(local_body_id,local_body_name, district_id, local_body_type_id) VALUES
(1,'Alappuzha',1,2),
(2,'Chengannur',1,2),
(3,'Cherthala',1,2),
(4,'Harippad',1,2),
(5,'Cherthala',1,2),
(6,'Kayamkulam',1,2),
(7,'Mavelikara',1,2);
