#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/static/css/org.css"/>
#+TITLE: Wemebox Documentation
* Getting started
   1. Download the the zip file from http://www.wemebox.com/r/downloads.html for your Operating System. It has binaries for linux, windows, and mac (32 bit and 64 bit)
   2. Extract the file and open the directory
   3. Once you run your binary open http://127.0.0.1:8080  for home page and http://127.0.0.1:8080/admin for admin page 
   4. Default login credentials will be *username:* admin *password:* root123
* Adding Pages
   1. Pages can be modified under Pages menu item from admin area or directly from html/ directory
   2. Static files such as css,javascript,images,videos must be added to */static* directory
* Base Pages
  Base pages are the templates for static pages. Base pages must have template blocks in place to add content from your static page like given below
#+BEGIN_SRC 
{{block "block-name" .}} {{end}} 

 #+END_SRC
You can use your own block names or just use the default block names generated automatically like given below

#+BEGIN_SRC 
 {{block "content" .}}{{end}}

 #+END_SRC

* Static Pages
  Static pages inherit a *base page*. Contents in the static pages template blocks appear in 

#+BEGIN_SRC
{{define "content"}}{{end}}
#+END_SRC

  
  
* Template Pages
  Template pages are templates for Markdown and Dynamic pages. Template pages inherit their layout from a *Base Page* like static page.
  Template page will have the following tags.  *.HtmlContent* tag will contain the converted html content from the markdown or dynamic page input

#+BEGIN_SRC 
 {{define "title"}}{{.Title}}{{end}}
{{define "content"}}
    {{.HtmlContent}}
{{end}}

 #+END_SRC


* Markdown pages
  Markdown pages are for markdown content. More information on markdown format can be found here: [[https://en.wikipedia.org/wiki/Markdown][Markdown]]
  
  1. *Title* can be used to specify the page title.
  2. *Url Slug* is for *SEO*.It is the unique url for the markdown page. It can be autogenerated from title or it can be any unique SEO friendly title
  3. *Base File* is the base page layout
  4. *Template file* is the template page for the markdown content
  5. The markdown editor can be used to enter the markdown content and click preview to view how the content will look like.

* Dynamic pages
  Dynamic pages can be used to create web pages just like a text editor.
  
  1. *Title* can be used to specify the page title.
  2. *Url Slug* is for *SEO*.It is the unique url for the markdown page. It can be autogenerated from title or it can be any unique SEO friendly title
  3. *Base File* is the base page layout
  4. *Template file* is the template page for the markdown content
  5. The text editor is used to enter the content that is needed for the page

* Raw Pages
  Sometimes you might want to create html pages wuth your favorite website creator application.
  You create the raw page with static page format and point the url to */r/filename.html*

* Standalone Pages
  If you want to create a standlone page, which is pure html file, just create the html file and point the url to */sp/filename.html*
  
     
* Image Files
  
  Image files can be added by clicking on the *Files* and then *Add Images*

* CSS editor
  
  You can edit javascript files from *Files* -> *CSS*. Enter the file path to edit or create a new file.
  All files are *saved in static directory*

* Javascript editor
  
  You can edit javascript files from *Files* -> *Javascript*. Enter the file path to edit or create a new file.
  All files are *saved in static directory*

* Config

  Website configurations can be found in config.yml file.

  - *port:* 8080 (default port is 8080 for development. If you set ssl true, the webserver will be started at port 443)

  - *ssl*: false (For development set this to false. When this is set to true, the application will automatically setup ssl certificate for you)

  - *compress*: true (Static files will be compressed by default for faster downloads)   *Note:* If you are using your own webserver like nginx, just set this to false

  - *dev*: This config setting is set to true while you are developing on your Desktop computer. Set this to true while deploying
    
  - *domain*: Set this value if you are using "https" in production. Use top level domain name E.G:mydomain.com
